classes/Gems/Project/ProjectSettings.php

DIRECTORY_SEPARATOR instead of DS

Fixed incorrect constant used

---

classes/Gems/Tracker/Engine/AnyStepEngine.php

It is now possible to use any round for valid from and calculation will allways consider all rounds instead of only future rounds

#162: Valid from can use future round too

---

classes/Gems/Model/RespondentModel.php
classes/Gems/Snippets/Respondent/ChangeRespondentOrganization.php
classes/Gems/Util/DbLookup.php
tests/classes/Gems/Model/DateFieldModelTest.php
tests/classes/Gems/Model/DateFieldModelTest.sql
tests/classes/Gems/Model/DateFieldModelTest.xml
tests/classes/Gems/Model/RespondentModelTest.php
tests/classes/Gems/Model/RespondentModelTest.sql
tests/classes/Gems/Model/RespondentModelTest.xml

Make options available to select work as expected
Issue #195

Issue #195 Change organization  of a patient bugfix

---

classes/Gems/Loader/LoaderAbstract.php
classes/Gems/Model.php
classes/Gems/Snippets/SnippetLoader.php
classes/Gems/Tracker.php
classes/Gems/Tracker/Model/RoundModel.php
classes/Gems/Tracker/Source/LimeSurvey1m9Database.php
classes/Gems/Tracker/Source/LimeSurvey1m9FieldMap.php
classes/Gems/Tracker/Source/LimeSurvey2m00Database.php
tests/classes/Gems/Model/Translator/RespondentAnswerTranslatorTest.php
tests/classes/Gems/Tracker/Source/LimeSurvey1m9FieldMapTest.php

- Can use Zalt\ProjectOverloader as PluginLoader
- Some dependency shifting

Changes in Gemstracker for use in Zend Expressive

---

classes/Gems/Event/Survey/BeforeAnswering/FillTrackFieldAnswers.php
tests/classes/Gems/Event/Survey/BeforeAnswering/FillTrackFieldAnswersTest.php
tests/classes/Gems/Event/Survey/BeforeAnswering/FillTrackFieldAnswersTest.php.php

Changes from master to 1.8.4-p1

---

classes/Gems/Default/UpdateSurveyAction.php
classes/Gems/Menu/MenuAbstract.php
classes/Gems/Snippets/Survey/SurveyCompareSnippet.php
classes/Gems/Tracker/Source/LimeSurvey1m9FieldMap.php
classes/Gems/Tracker/Source/LimeSurvey2m00Database.php
classes/Gems/Tracker/Source/LimeSurvey2m00FieldMap.php
classes/Gems/Util/DbLookup.php
controllers/UpdateSurveyController.php

where you can compare an old and new survey and transfer answers and tokens to the new version
@jvangestel do we want this added to the core? does it need adjustment?

Added a survey update feature

---

classes/Gems/Actions/SourceAction.php
classes/Gems/Batch/BatchRunner.php
classes/Gems/Batch/BatchRunnerLoader.php
classes/Gems/Config/Menu.php
classes/Gems/Config/Route.php
classes/Gems/Layout/LayoutSettings.php
classes/Gems/LegacyConfigProvider.php

2.x layout settings

---

.github/workflows/php.yml
composer.json
phpstan-baseline.neon
phpstan.neon.dist
psalm.xml

This should fix the composer issues when running the github action on a pull request, and it adds phpstan as a separate job.
See https://github.com/rvm-peercode/gemstracker-library/actions/runs/5443224726

2.x GitHub actions improvement

---

.github/workflows/php.yml
src/Config/Route.php
src/Handlers/ParticipateHandler.php
src/Legacy/CurrentUserRepository.php
src/Model.php
src/Screens/Respondent/Subscribe/EmailOnlySubscribe.php
src/Screens/Respondent/Unsubscribe/EmailOnlyUnsubscribe.php
src/Screens/ScreenRepository.php
src/Site/SiteUtil.php
src/Snippets/Subscribe/EmailSubscribeSnippet.php
src/Snippets/Unsubscribe/EmailUnsubscribeSnippet.php

Finish refactor of subscribe/unsubscribe functionality
Still todo: Adding the ThrottleValidator

2.x subscribe2

---

src/Snippets/Token/ShowTrackTokenSnippet.php

Fix voor https://trello.com/c/18fykHqt/367

Correct link for Edit button

---

src/Tracker/Source/LimeSurvey3m00Database.php

Even if no completed tokens were found.

LimeSurvey3m00Database: Always return array from getCompletedTokens()

---

src/Tracker/Token.php
src/Tracker/Token/LaminasTokenSelect.php
src/Tracker/TrackEvent/BeforeAnsweringAbstract.php

With these changes, I get my previous answers as new row in the database, but they aren't used yet. I suspect a language mismatch.

2.x fix token prev

---

phpstan-baseline.neon
phpstan.neon.dist

Try harder to avoid problems in new or refactored code.

phpstan: Increase level to 5 and update baseline

---

configs/db/tables/gems__user_password_history.50.sql
src/ConfigProvider.php
src/Handlers/Auth/ChangePasswordHandler.php
src/Handlers/Auth/ResetPasswordChangeHandler.php
src/User/DbUserDefinitionAbstract.php
src/User/LdapUserDefinition.php
src/User/PasswordChecker.php
src/User/PasswordHistoryChecker.php
src/User/RadiusUserDefinition.php
src/User/User.php
src/User/UserDefinitionAbstract.php
src/User/UserDefinitionInterface.php
src/User/Validate/NewPasswordValidator.php

Added functionality to track a password history. We keep track of a configurable number of passwords, and when changing the password, these passwords cannot be reused.

2.x passwordhistory

---

src/Snippets/Agenda/AppointmentShowSnippet.php
src/Snippets/Agenda/AppointmentsTableSnippet.php
src/Snippets/Agenda/CalendarTableSnippet.php

Remove stopwatch.png references and replace with font awesome icon

Remove stopwatch.png references and replace with font awesome icon

---

src/Model/Dependency/AppointmentCareEpisodeDependency.php
src/Model/Dependency/CommJob/Senderdependency.php
src/Model/Dependency/Condition/ClassDependency.php
src/Model/Dependency/Condition/RoundDependency.php
src/Model/Dependency/Condition/TypeDependency.php
src/Model/Dependency/StaffUserClassDependency.php
src/Model/StaffModel.php
src/Tracker/Engine/TrackEngineAbstract.php
src/Tracker/Model/SurveyMaintenanceModel.php

Use the Zalt DependencyAbstract, fixes an inline javascript issue.

2.x refactor conditions

---

templates/gems/request-password-reset.html.twig

Adds back the original text to the password reset page

Add text to password reset page

---

src/Handlers/TrackBuilder/SourceHandler.php
src/Model/TrackBuilder/SourceModel.php
src/Model/Type/EncryptedField.php

Extracted SourceModel from SourceHandler

Extracted SourceModel from SourceHandler

---

src/Factory/ReflectionAbstractFactory.php
src/Handlers/Respondent/RespondentHandler.php
src/Model/Respondent/RespondentModel.php
src/Snippets/ModelFormSnippetAbstract.php

2.x respondend page changes

---

phpstan-baseline.neon
src/Export/RespondentExport.php
src/Handlers/Respondent/RespondentTrackHandler.php
src/Handlers/Respondent/TrackHandler.php
src/Snippets/Track/TracksSnippet.php
src/Snippets/Tracker/DeleteTrackSnippet.php
src/Snippets/Tracker/ShowTrackUsageSnippet.php
src/Snippets/Tracker/TrackUsageOverviewSnippet.php
src/Tracker.php
src/Tracker/Model/AddTrackFieldsTransformer.php
src/Tracker/Model/RespondentTrackModel.php
src/Tracker/Model/Transform/AddAnswersTransformer.php
src/Tracker/Snippets/EditTrackSnippetAbstract.php
src/Tracker/Snippets/ShowTrackUsageAbstract.php
src/Tracker/Source/SourceInterface.php
src/Tracker/SurveyModel.php
src/Util/DbLookup.php

Migrated the RespondentTrackModel. Some changes which require some attention:
- In the AddTrackFieldsTransformer I removed the ability to track the change count, which was possible in the ModelAbstract. However, I could not find an equivalent function.

RespondentTrackModel migrated to zalt-model

---

phpstan-baseline.neon
src/Config/Route.php
src/Handlers/Overview/ConsentPlanHandler.php
src/SnippetsActions/Show/ShowAsTableAction.php

Now we can disable the row counts, which speeds up the page.
To Do: Selecting a single organization still shows data from all organizations.

ConsentPlanHandler: Rewrite to use Laminas

---

src/Handlers/Setup/ProjectInformationHandler.php
src/Versions.php

Since gemstracker is a library, we can assume it is installed via composer.

Versions: Get gemstracker version from composer

---

src/Tracker/Model/Dependency/OtherFieldValuesDependency.php

Fix issue when showing track field, seen in CP-register

OtherFieldValuesDependency: formatValues() should accept array

---

configs/db/tables/gems__app_versions.100.sql
src/Cache/HelperAdapter.php
src/Repository/AppVersionRepository.php

This provides fast access to the application versions that have been used in the history of the application.

Create AppVersionRepository and accompanying table

---

.github/workflows/php.yml
composer.json

Run phpstan with both the latest stable versions of packages, and the minimum version as specified in composer.json.

Improve Q&A

---

src/Snippets/User/EmbeddedUserTestUrlForm.php
src/User/Embed/Auth/HourKeyAes256.php
src/User/Embed/Auth/MinuteKeyAes256.php
src/User/Embed/Auth/TimeKeyAes256Abstract.php
src/User/Embed/EmbeddedAuthInterface.php
tests/User/Embed/Auth/TimeKeyAes256AbstractTest.php

Ported from the master branch and updated for 2.x.

Embedded authentication via Aes encryption

---

src/AuthNew/Adapter/EmbedAuthentication.php
src/Handlers/Auth/EmbedLoginHandler.php
src/Snippets/User/EmbeddedUserTestUrlForm.php
src/User/Embed/Auth/TimeKeyAes256Abstract.php
src/User/Embed/EmbeddedAuthAbstract.php
src/User/Embed/UpdatingAuthInterface.php

This variant didn't work properly yet.

Support getting usr and pid via encrypted string
